#!/bin/sh
# load $XDG_CONFIG_HOME/X11/xprofile file if it exists; otherwise, load ~/.xprofile
[ -f "$HOME"/X11/xprofile ] && source "$HOME"/X11/xprofile || source ~/.xprofile

#exec qtile start
exec dwm
